Santis catalyst/paraview fixes for icon compatibility

diff --git a/recipes/paraview-icon/gh200/post-install b/recipes/paraview-icon/gh200/post-install
--- a/recipes/paraview-icon/gh200/post-install
+++ b/recipes/paraview-icon/gh200/post-install
@@ -1,97 +1,96 @@
 #!/bin/bash
 
-echo "====================================="
-echo "=====     post install hook          "
-echo "====================================="
+# =====================================
+# we output messages to stdout and also stderr to simplify debugging since logs are usually in 
+# separate files and we want to see where errors are happening in the script
+function debug_output1() {
+    echo
+    echo "=====================================" 
+    echo "===== $1"
+    echo "====================================="
+} 
+
+function debug_output() {
+    debug_output1 $1 | tee >(cat >&2)
+} 
+
+# =====================================
+debug_output "post install hook"
 mount_path={{ env.mount }}
 echo RUNNING IN $mount_path
 config_path={{ env.config }}
 echo config is in $config_path
 
-echo
-echo "====================================="
-echo "=====   environment variables        "
-echo "====================================="
+# =====================================
+debug_output "environment variables"
 printenv
 
-echo
-echo "====================================="
-echo "=====   create post file {{ env.mount }}/post "
-echo "====================================="
+# =====================================
+debug_output "create post file $mount_path/post"
 echo "$(date)" > "$mount_path/post"
 
-echo
-echo "====================================="
-echo "=====   set vars we need frequently  "
-echo "====================================="
+# =====================================
+debug_output "set vars we need frequently"
 HOME=$(pwd)
 SPACK_CMD="spack -C $config_path"
 
-echo
-echo "====================================="
-echo "===== list all spack packages        "
-echo "====================================="
+# =====================================
+debug_output "list all spack packages"
 $SPACK_CMD find -flv
 
-echo
-echo "====================================="
-echo "===== source spack environment setup "
-echo "====================================="
+# =====================================
+debug_output "list all spack environments"
 SPACK_ROOT=$( $SPACK_CMD location -r )
 source $SPACK_ROOT/share/spack/setup-env.sh
 
-echo
-echo "====================================="
-echo "===== convert stackinator environment into a package "
-echo "====================================="
+# =====================================
+debug_output "convert stackinator environment into a package"
 python3 $HOME/store/meta/recipe/env-to-package.py $HOME/store/meta/recipe/environments.yaml 
+# remove explicit gcc version as this causes a concretization error
+sed -i 's/%gcc//g' $(spack location -p temppackage)/package.py
 
-echo
-echo "====================================="
-echo "===== create build-env "
-echo "====================================="
+# =====================================
+debug_output "create build-env"
 BUILD_ENV=$mount_path/paraview-buildenv.rc
 SPEC="temppackage %gcc@12.3"
-$SPACK_CMD -e $HOME/environments/pv-egl-cuda/ env activate --sh
-$SPACK_CMD -e $HOME/environments/pv-egl-cuda/ add $SPEC
-$SPACK_CMD -e $HOME/environments/pv-egl-cuda/ concretize
-$SPACK_CMD -e $HOME/environments/pv-egl-cuda/ build-env --dump $BUILD_ENV "$SPEC"
+$SPACK_CMD -e $HOME/environments/icon-dsl-paraview/ env activate --sh
+$SPACK_CMD -e $HOME/environments/icon-dsl-paraview/ add $SPEC
+$SPACK_CMD -e $HOME/environments/icon-dsl-paraview/ concretize
+$SPACK_CMD -e $HOME/environments/icon-dsl-paraview/ build-env --dump $BUILD_ENV "$SPEC"
 
-echo
-echo "====================================="
-echo "===== checkout paraview/vtk/vtkm branches "
-echo "====================================="
+# =====================================
+debug_output "create $mount_path/src dir"
 mkdir -p $mount_path/src
 cd $mount_path/src
+
+# =====================================
+debug_output "clone paraview"
+PARAVIEW_VERSION=5.12.0
 
 # get default paraview master branch
 git clone https://gitlab.kitware.com/paraview/paraview.git
 cd $mount_path/src/paraview
-git submodule update --init --recursive
-git checkout v5.12.0-RC3
 
-echo "====================================="
-echo "===== change to master branch of VTK "
-echo "====================================="
+debug_output "switch to version ${PARAVIEW_VERSION} from tag v${PARAVIEW_VERSION}"
+git checkout -b ${PARAVIEW_VERSION} v${PARAVIEW_VERSION}
+git submodule update --init --recursive
+
+# =====================================
+debug_output "Update VTK Submodules"
 cd $mount_path/src/paraview/VTK
 git submodule update 
 
-echo "====================================="
-echo "===== change to 2.1.0 branch of vtk-m "
-echo "====================================="
+# =====================================
+debug_output "change to 2.1.0 branch of vtk-m"
 cd $mount_path/src/paraview/VTK/ThirdParty/vtkm/vtkvtkm/vtk-m
 git checkout v2.1.0
 
-echo
-echo "====================================="
-echo "===== source build-env "
-echo "====================================="
+# =====================================
+debug_output "source build-env"
 source $BUILD_ENV
 
-echo
-echo "====================================="
-echo "===== run cmake on paraview "
-echo "====================================="
+# =====================================
+debug_output "run cmake on paraview"
 mkdir -p $mount_path/build/pv && cd $mount_path/build/pv
 cmake -G Ninja \
     -DCMAKE_INSTALL_PREFIX=$mount_path/paraview \
@@ -102,6 +101,7 @@ cmake -G Ninja \
     -DVTK_OPENGL_HAS_EGL=ON \
     -DPARAVIEW_USE_PYTHON=ON \
     -DPARAVIEW_ENABLE_CATALYST=YES \
+    -Dcatalyst_DIR=$($SPACK_CMD location -i libcatalyst) \
     -DPARAVIEW_USE_CUDA=OFF \
     -DCMAKE_CUDA_ARCHITECTURES=90 \
     -DPARAVIEW_BUILD_WITH_EXTERNAL=ON \
@@ -122,10 +122,8 @@ cmake -G Ninja \
     # -DVTK_MODULE_ENABLE_VTK_IOCGNSReader=NO \
     # -DVTK_MODULE_ENABLE_VTK_ioss=NO \
 
-echo
-echo "====================================="
-echo "===== build and install paraview "
-echo "====================================="
+# =====================================
+debug_output "build and install paraview"
 ninja 
 ninja install
 ninja clean
@@ -133,18 +131,11 @@ ninja clean
 PARAVIEW_DIR=$mount_path/paraview
 PARAVIEW_VERSION=5.12
 
+# =====================================
+debug_output "build icon"
 
-echo
-echo "====================================="
-echo "===== build icon  "
-echo "====================================="
-
-
-
-echo
-echo "====================================="
-echo "===== build plugin  "
-echo "====================================="
+# =====================================
+debug_output "build paraview plugin"
 cd $mount_path/src
 git clone https://github.com/jfavre/ParaViewGadgetPlugin
 mkdir $mount_path/build/ParaViewGadgetPlugin && cd $mount_path/build/ParaViewGadgetPlugin
@@ -157,16 +148,13 @@ ninja
 ninja install
 ninja clean
 
-echo
-echo "====================================="
-echo "===== set permissions  "
-echo "====================================="
+# =====================================
+debug_output "set permissions"
 chmod -R a+r $BUILD_ENV
 chmod -R a+r $mount_path/src
 chmod -R a+r $mount_path/build
 chmod -R a+r $mount_path/paraview
 chmod -R a+r $mount_path/paraview-plugins
 
-echo "====================================="
-echo "========  Done  ========"
-echo "====================================="
+# =====================================
+debug_output "Done"
